instances:
  type: swe_bench # when you run swe benches
  subset: verified # full, or lite
  split: test # or dev for development, but verified version only has test split
  filter: ^(matplotlib__matplotlib-25122|scikit-learn__scikit-learn-14894)$ # regrex used for filter the instances by instance id in swebench
  slice: ":2" # after filter, only select like list[slice] instances
  shuffle: true # randomize the instances (before filtering and slicing)
  evaluate: false # evaluate the instances
output_dir: trajectories/simple_test

